#!/bin/bash

mode=$1

case $mode in

  power_max | 0)
    echo -n "Maximum powersave mode"$'\n'
    energy=255
    energy_bias=15
    turbo=1
    ;;

  power | 1)
    echo -n "Powersave mode"$'\n'
    energy=200
    energy_bias=12
    turbo=1
    ;;

  balance | 2)
    echo -n "Balanced mode"$'\n'
    energy=145
    energy_bias=10
    turbo=0
    ;;
    
  performance | 3)
    echo -n "Performance mode"$'\n'
    energy=balance_performance
    energy_bias=8
    turbo=0
    ;;

  performance_max | 4)
    echo -n "Maximum performance mode, don't run it for too long"$'\n'
    energy=0
    energy_bias=0
    turbo=0
    ;;

  --help | "")
    echo -n "Usage: cpu [OPTION]"$'\n'
    echo -n "cpu power_max or cpu 0 for maximum powersaving mode"$'\n'
    echo -n "cpu power or cpu 1 for powersaving mode"$'\n'
    echo -n "cpu balance or cpu 2 for balanced performance mode"$'\n'
    echo -n "cpu performance or cpu 3 for performance mode, default settings of most kernels"$'\n'
    echo -n "cpu performance_max or cpu 4 for maximum performance, very aggressive on the cpu"$'\n'
	exit 1
    ;;

  *)
    echo -n "Wrong argument"$'\n'
    exit 1
    ;;
    
esac

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo $turbo > /sys/devices/system/cpu/intel_pstate/no_turbo

for i in {0..7}
do
	echo -n $energy > /sys/devices/system/cpu/cpufreq/policy$i/energy_performance_preference
done

for i in {0..7}
do
	echo -n $energy_bias > /sys/devices/system/cpu/cpu$i/power/energy_perf_bias
done

