#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

mode=$1

case $mode in

  powersave)
    echo -n "Powersave mode"$'\n'
    governor=power
    turbo=1
    ;;

  conservative)
    echo -n "Conservative mode"$'\n'
    governor=balance_performance
    turbo=1
    ;;

  performance)
    echo -n "Performance mode"$'\n'
    governor=balance_performance
    turbo=0
    ;;

  *)
    echo -n "Wrong argument"$'\n'
    exit 1
    ;;
esac

for i in {0..7}
do
	echo $governor > /sys/devices/system/cpu/cpufreq/policy$i/energy_performance_preference
done
echo $turbo > /sys/devices/system/cpu/intel_pstate/no_turbo
